# Generated by Django 2.2.5 on 2019-09-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='level',
            new_name='depth',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='titel',
            new_name='title',
        ),
    ]
